services:
  - type: web
    name: photo-capture-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://location_1698_user:Scmgt1Keu8Y4SgFsoTM0OVG6PKAUg1Hu@dpg-d1fbfsfgi27c73ckorkg-a/location_1698"

